name: GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
        # In all these caching steps we introduce a CACHE_VERSION secret
        # in the key which is a workaround to the fact that
        # it's not possible to manually invalidate cache as of Dec 2021.
        # See issue https://github.com/actions/cache/issues/2 and StackOverflow
        # https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions
      - name: Caching Poetry
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.local
          key: ${{ secrets.CACHE_VERSION }}-poetry-${{ runner.os }}-${{ matrix.python_version }}
      - name: Install poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: curl -sSL https://install.python-poetry.org/ | python3 -
      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: dependency-cache
        uses: actions/cache@v2
        id: dependency-cache
        with:
          path: ~/.cache/pypoetry
          key: ${{ secrets.CACHE_VERSION }}-venv-${{ runner.os }}-${{ matrix.python_version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure cache is healthy
        if: steps.dependency-cache.outputs.cache-hit == 'true'
        run: poetry run pip --version
      - name: Install Dependencies
        run: poetry install

      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

      - name: Build doc
        run: poetry run sphinx-build -M html ./docs/ ./docs/_build
      - name: Deploy Doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: "Deployment ${{ steps.prepare_tag.outputs.tag_name }}"
