name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ursamajorlab/impish-python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        # In all these caching steps we introduce a CACHE_VERSION secret
        # in the key which is a workaround to the fact that
        # it's not possible to manually invalidate cache as of Dec 2021.
        # See issue https://github.com/actions/cache/issues/2 and StackOverflow
        # https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions
      - name: Caching Poetry
        uses: actions/cache@v3
        id: poetry-cache
        with:
          path: ~/.local
          key: ${{ secrets.CACHE_VERSION }}-poetry-${{ runner.os }}-${{ matrix.python_version }}
      - name: Install poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: curl -sSL https://install.python-poetry.org/ | python3 -
      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: dependency-cache
        uses: actions/cache@v3
        id: dependency-cache
        with:
          path: ~/.cache/pypoetry
          key: ${{ secrets.CACHE_VERSION }}-venv-${{ runner.os }}-${{ matrix.python_version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure cache is healthy
        if: steps.dependency-cache.outputs.cache-hit == 'true'
        run: poetry run pip --version
      - name: Install Dependencies
        run: poetry install
      - name: Build and publish
        run: |
          poetry build
          poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
